sudo: false

language: node_js

branches:
  only:
    - master

before_script:
  - npm install

script:
  - htmlhint **/*.html
  - jshint **/*.{js,json}
  - csslint **/*.css
  - mocha javascripts/tests/*.js
