sudo: false

language: node_js

branches:
  only:
    - master

before_script:
  - npm install

script:
  - htmlhint index.html
  - jshint javascripts/**/*.{js,json}
  - csslint stylesheets/**/*.css
  - mocha javascripts/tests/*.js
